resresources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/Quirio/Concourse_tutorial
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
